[env:esp32doit-devkit-v1]
platform = espressif32@6.9.0
board = esp32doit-devkit-v1
framework = arduino

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.3
    tzapu/WiFiManager @ ^2.0.16
    adafruit/Adafruit NeoPixel @ ^1.11.0

; Uncomment to erase all flash before uploading (clears saved WiFi/preferences)
; board_build.flash_erase = true

upload_port = COM3
monitor_port = COM3
monitor_speed = 115200